#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}
DATE=`date +%Y-%m-%d`

# Tag and push image for each additional tag
docker tag $IMAGE_NAME ${repoName}:${DATE}
docker push ${repoName}:${DATE}
